const userConstants = {
    GET_STATE_REQUEST: 'GET_STATE_REQUEST',
    GET_STATE_SUCCESS: 'GET_STATE_SUCCESS',
    GET_STATE_FAILURE: 'GET_STATE_FAILURE',

    GET_COUNTY_REQUEST: 'GET_COUNTY_REQUEST',
    GET_COUNTY_SUCCESS: 'GET_COUNTY_SUCCESS',
    GET_COUNTY_FAILURE: 'GET_COUNTY_FAILURE',

    GET_ZIP_REQUEST: 'GET_ZIP_REQUEST',
    GET_ZIP_SUCCESS: 'GET_ZIP_SUCCESS',
    GET_ZIP_FAILURE: 'GET_ZIP_FAILURE',
}
export default userConstants;